spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/crypto_tracker}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:aaru1234}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# External APIs
api.coingecko.base=https://api.coingecko.com/api/v3
api.coinpaprika.base=https://api.coinpaprika.com/v1
api.dexscreener.base=https://api.dexscreener.com/latest/dex
api.coinlore.base=https://api.coinlore.net/api